action.yml: add check for auth info
This is effectively a noop right now, since the api-key input is
required. This is in preparation for merging #24 where you can specify
an api-key or oauth credentials.

Signed-off-by: Will Norris <will@tailscale.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -17,6 +17,12 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: Check Auth Info Empty
+      if: ${{ inputs.api-key == '' }}
+      shell: bash
+      run: |
+        echo "::error title=⛔ error hint::API Key empty. Maybe you need to populate it in the Secrets for your workflow, see more in https://docs.github.com/en/actions/security-guides/encrypted-secrets"
+        exit 1
     - uses: actions/setup-go@v4.0.0
       with:
         go-version: 1.21.6
